{{- if not .Values.component.extendedSettings.externalBox }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.component.name }}
  name: {{ .Values.component.name }}
  annotations:
    fluxcd.io/automated: 'true'
    {{- if .Values.annotations }}
    th2.exactpro.com/antecedent : {{ .Values.annotations }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.component.name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if .Values.annotations }}
        th2.exactpro.com/antecedent : {{ .Values.annotations }}
        {{- end }}
      labels:
        app: {{ .Values.component.name }}
    spec:
      containers:
      - image: {{ .Values.component.image }}
        name: {{ .Values.component.name }}
        {{- if not .Values.component.prometheus }}
        ports:
        - name: metrics
          containerPort: 9752
        {{- else }}      
        {{- if .Values.component.prometheus.enabled }}
        ports:
        - name: metrics
          {{- if .Values.component.prometheus.port }}
          containerPort: {{ .Values.component.prometheus.port }}
          {{- else }}
          containerPort: 9752
          {{- end }}
        {{- end }}
        {{- end }}
        resources:
          limits:
            memory: {{ .Values.component.extendedSettings.resources.limits.memory | default "200Mi" }}
            cpu: {{ .Values.component.extendedSettings.resources.limits.cpu | default "200m" }}
          requests:
            memory: {{ .Values.component.extendedSettings.resources.requests.memory | default "100Mi" }}
            cpu: {{ .Values.component.extendedSettings.resources.requests.cpu | default "50m" }}
        env:
        {{- if .Values.component.extendedSettings.envVariables }}
        {{- range $envName, $envValue := .Values.component.extendedSettings.envVariables }}
        - name: {{ $envName }}
          value: {{ $envValue | quote }}
        {{- end }}
        {{- end }}
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: CASSANDRA_PASS
          valueFrom:
            secretKeyRef:
              name: cassandra
              key: cassandra-password
        volumeMounts:
        - name: logging-volume
          mountPath: /home/etc/log4j.properties
          subPath: log4j.properties
        - name: configs
          mountPath: /var/th2/config/
        {{- range $volume := .Values.component.extendedSettings.mounting }}
        - name: {{ $volume.pvcName | lower }}
          mountPath: {{ $volume.path | quote }}
        {{- end }}
      volumes:
      {{- range $volume := .Values.component.extendedSettings.mounting }}
      - name: {{ $volume.pvcName | lower }}
        persistentVolumeClaim:
          claimName: {{ $volume.pvcName }}
      {{- end }}
      - name: logging-volume
        configMap:
          name: java-logging-config
      - name: configs
        projected:
          sources:
          {{- if .Values.component.extendedSettings.hostNetwork }}
          - configMap:
              name: rabbit-mq-external-app-config
          - configMap:
              name: cradle-external
          {{ else }}
          - configMap:
              name: rabbit-mq-app-config
          - configMap:
              name: cradle
          {{- end }}
          - configMap:
              name: {{ .Values.component.name }}-app-config
          {{- range $dictionary := .Values.component.dictionaries }}
          - configMap:
              name: {{ $.Values.component.name }}-{{ $dictionary.name | lower }}-dictionary
          {{- end }}
      imagePullSecrets:
      - name: th2-solution
      - name: th2-core
      - name: th2-proprietary
      - name: th2-schema-test
      {{- if .Values.component.extendedSettings.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
  revisionHistoryLimit: 2
{{- end }}
